### ISSUE TITLE
Any future?

### ISSUE THREAD

**Issue by dumblob** [relab/smartMerge#1]
Is this being used anywhere in production? Or is there any commercial (or opensource) alternative? Or was it superseeded by something else?

Thanks!

**Comment by leandernikolaus** [comment]
Hi @dumblob,

thanks for your interest.
The implementations in this repository are meant to allow fine graned benchmarks of different algorithms and are not intended for production.
I am not aware of any commercial or open-source software that currently uses these algorithms.

Please also note, that the repository does not contain an implementation of FreeStore, which would be beneficial for completeness.

Hope this answers your question.

Leander

**Comment by dumblob** [comment]
Ah, I see. Thanks for your answers!

Closing for lack of actionable items.
